AWSTemplateFormatVersion: '2010-09-09'
Description: This template describes a single EC2 instance inside a VPC with a route table and SG to access internet

Parameters:
  vpcCidrBlock:
    Description: VPC cidr range
    Type: String
    Default: 192.168.0.0/16

  subnetCidrBlock:
    Description: subnet cidr range
    Type: String
    Default: 192.168.0.0/16

  myKeyPair: 
    Type: AWS::EC2::KeyPair::KeyName 
    Description: The name of your ssh keypair

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpcCidrBlock

  myPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock:
        Ref: subnetCidrBlock
      MapPublicIpOnLaunch: true

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
  
  myAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myVPC
      InternetGatewayId:
        Ref: myInternetGateway
  
  myPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC

  myRoute:
    Type: AWS::EC2::Route
    DependsOn: myInternetGateway
    Properties:
      RouteTableId:
        Ref: myPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: myInternetGateway

  mySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: myPublicSubnet
      RouteTableId:
        Ref: myPublicRouteTable

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref myVPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 1
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  myEC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bdb828fd58c52235 # This  amazon linux 2018.03 in us-west-1
      InstanceType: t2.micro
      KeyName: 
        Ref: myKeyPair
      SubnetId:
        Ref: myPublicSubnet
      SecurityGroupIds: [!Ref mySecurityGroup]

Outputs:
  myEC2InstancePublicIP:
    Value: !GetAtt myEC2Instance.PublicIp